### ISSUE TITLE
Conflict with TTT2 (Base) when purchased for non-Traitor roles

### ISSUE THREAD

**Issue by GitCuckoo** [NicolasLutz/ttt_potOfGreed#1]
Howdy!

I've just given this a spin, however whenever I add it into the shop of a role other than Traitor and try to purchase it, it generates a script error (the item is not given; no other items are given).

Purchasing it as a Traitor, from the traitor shop, works fine. Didn't work when I tried it as a "special" traitor (i.e. Vampire), nor as Jester, nor as Necromancer:

```
File exists in two addons - possible conflicts! gamemodes/terrortown/gamemode/server/sv_shop.lua (TTT2 v0.6.3 and ttt_potOfGreed)

[ERROR] lua/weapons/weapon_ttt_potofgreed.lua:70: attempt to get length of local 'equipmentTable' (a nil value)
  1. WasBought - lua/weapons/weapon_ttt_potofgreed.lua:70
   2. callback - gamemodes/terrortown/gamemode/server/sv_shop.lua:127
    3. GiveEquipmentWeapon - gamemodes/terrortown/gamemode/server/sv_player_ext.lua:486
     4. OrderEquipment - gamemodes/terrortown/gamemode/server/sv_shop.lua:124
      5. func - gamemodes/terrortown/gamemode/server/sv_shop.lua:156
       6. unknown - lua/includes/extensions/net.lua:32
```

![20200309194945_1](https://user-images.githubusercontent.com/61295682/76251837-a477d580-623f-11ea-8445-36685bdbcdc6.jpg)

**Comment by DrLutzi** [comment]
Thanks for noticing! I'll look into that
